version: "3.9"

services:
  backend:
    environment:
      NODE_ENV: "development"
      LOG_LEVEL: "verbose"
    volumes:
      # Mount source code for development (if you want hot reload later)
      - ./backend/src:/usr/src/app/src:ro
    command: >
      sh -c "
        echo '🔄 Development mode: Running database migrations...' &&
        npx prisma migrate deploy &&
        echo '✅ Migrations completed' &&
        echo '🌱 Running database seed...' &&
        (npm run prisma:seed || echo '⚠️  Seeding failed or skipped') &&
        echo '🚀 Starting application in development mode...' &&
        node dist/src/main.js
      "
    # Override healthcheck for development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  postgres:
    # Add more verbose logging for development
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres